import './globals.css';

export const metadata = {
  title: 'FinSathi® | Your AI Financial Advisor',
  description: 'AI-powered personal finance mentor for Indian users. Get a complete financial plan — health score, FIRE planning, tax optimization, MF analysis, and couple\'s planning — free forever.',
  keywords: 'financial advisor, FIRE planning, tax calculator India, mutual fund analysis, personal finance India',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <meta name="theme-color" content="#001525" />
      </head>
      <body className="bg-navy-900 text-navy-50 min-h-screen flex flex-col antialiased">
        {/* Navigation */}
        <nav className="nav-blur fixed top-0 left-0 right-0 z-50 border-b border-navy-50/5">
          <div className="max-w-7xl mx-auto px-4 sm:px-6">
            <div className="flex items-center justify-between h-14">
              <a href="/" className="flex items-center gap-2">
                <span className="text-xl font-serif font-bold text-gradient-teal">FinSathi</span>
                <span className="text-[8px] text-navy-50/30 font-semibold tracking-wider">®</span>
              </a>

              <div className="hidden md:flex items-center gap-1">
                {[
                  { href: '/health-score', label: 'Health Score' },
                  { href: '/fire-planner', label: 'FIRE Planner' },
                  { href: '/tax-wizard', label: 'Tax Wizard' },
                  { href: '/mf-xray', label: 'MF X-Ray' },
                  { href: '/couples-planner', label: "Couple's Planner" },
                  { href: '/audit-trail', label: 'Audit Trail' },
                ].map((item) => (
                  <a
                    key={item.href}
                    href={item.href}
                    className="px-3 py-1.5 text-xs font-medium text-navy-50/60 hover:text-teal-200 transition-colors rounded-lg hover:bg-surface-container/50"
                  >
                    {item.label}
                  </a>
                ))}
              </div>

              {/* Mobile menu button */}
              <button className="md:hidden p-2 text-navy-50/60 hover:text-teal-200" id="mobile-menu-btn">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              </button>
            </div>
          </div>
        </nav>

        {/* Main content */}
        <main className="flex-1 pt-14">
          {children}
        </main>

        {/* SEBI Footer Disclaimer */}
        <footer className="mt-auto">
          <div className="w-full bg-amber-900/30 border-t border-amber-400/20 py-3 px-4">
            <div className="max-w-7xl mx-auto">
              <p className="text-[10px] text-amber-200/70 leading-relaxed text-center">
                ⚠️ AI Guidance Only — This analysis is generated by artificial intelligence and is for educational and informational purposes only.
                It does not constitute licensed financial advice, investment advice, or tax advice.
                Please consult a SEBI-registered investment advisor and a chartered accountant before making any financial decisions.
                FinSathi is not responsible for any financial outcomes based on this analysis.
              </p>
            </div>
          </div>
          <div className="bg-surface-container-lowest py-6 px-4 border-t border-navy-50/5">
            <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
              <div className="flex items-center gap-2">
                <span className="font-serif font-bold text-teal-200">FinSathi</span>
                <span className="text-xs text-navy-50/30">© 2025 All rights reserved</span>
              </div>
              <div className="flex items-center gap-4 text-xs text-navy-50/40">
                <span>Privacy Policy</span>
                <span>Terms of Service</span>
                <span>Disclaimer</span>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
