'use client';

import { FadeIn } from './animations/FadeIn';

export default function SEBIDisclaimer({ variant = 'banner' }) {
  const text = "⚠️ AI Guidance Only — This analysis is generated by artificial intelligence and is for educational and informational purposes only. It does not constitute licensed financial advice, investment advice, or tax advice. Please consult a SEBI-registered investment advisor and a chartered accountant before making any financial decisions. FinSathi is not responsible for any financial outcomes based on this analysis.";

  if (variant === 'inline') {
    return (
      <FadeIn direction="up" distance={15} className="mt-4 p-4 rounded-xl bg-amber-900/20 border border-amber-500/20 backdrop-blur-sm shadow-glass">
        <p className="text-xs text-amber-200/80 leading-relaxed font-medium">{text}</p>
      </FadeIn>
    );
  }

  return (
    <FadeIn direction="up" distance={0} once={true} duration={1} delay={0.5} className="w-full bg-amber-900/10 border-t border-amber-500/20 py-3 px-4 backdrop-blur-md">
      <div className="max-w-7xl mx-auto">
        <p className="text-[11px] text-amber-200/60 leading-relaxed text-center font-medium tracking-wide">{text}</p>
      </div>
    </FadeIn>
  );
}
