/**
 * Compliance Agent — SEBI regulatory guardrails
 */

const SEBI_DISCLAIMER = "⚠️ AI Guidance Only — This analysis is generated by artificial intelligence and is for educational and informational purposes only. It does not constitute licensed financial advice, investment advice, or tax advice. Please consult a SEBI-registered investment advisor and a chartered accountant before making any financial decisions. FinSathi is not responsible for any financial outcomes based on this analysis.";

export function applyComplianceGuardrails(module, results) {
  const guardrails = [];

  // Universal guardrails
  guardrails.push({ type: 'disclaimer', text: SEBI_DISCLAIMER });

  switch (module) {
    case 'health-score':
      guardrails.push({ type: 'note', text: 'Health scores are indicative and based on self-reported data. Actual financial health may vary.' });
      break;
    case 'fire-planner':
      guardrails.push({ type: 'note', text: 'Returns are assumed at historical averages (12% equity, 7% debt). Actual returns may vary significantly.' });
      guardrails.push({ type: 'note', text: 'Inflation is assumed at 6%. Tax implications on withdrawals are not included in this projection.' });
      if (results?.additionalSIPNeeded > 100000) {
        guardrails.push({ type: 'warning', text: 'The required additional SIP is very high. Consider extending your retirement horizon or reducing withdrawal target.' });
      }
      break;
    case 'tax-wizard':
      guardrails.push({ type: 'note', text: 'Tax calculations are based on FY2024-25 rates. Verify with a Chartered Accountant before filing.' });
      guardrails.push({ type: 'note', text: 'Surcharge and special provisions may apply based on your complete income profile.' });
      break;
    case 'mf-xray':
      guardrails.push({ type: 'note', text: 'Overlap analysis uses approximated holdings data. Actual fund compositions change quarterly.' });
      guardrails.push({ type: 'note', text: 'Past performance does not guarantee future returns. XIRR is based on historical data.' });
      break;
    case 'couples-planner':
      guardrails.push({ type: 'note', text: 'Tax optimization recommendations assume both partners file taxes independently.' });
      guardrails.push({ type: 'note', text: 'HRA claims must be supported by actual rent receipts and landlord PAN (>₹1L/year).' });
      break;
  }

  return { ...results, compliance: { guardrails, disclaimer: SEBI_DISCLAIMER } };
}
